# Setup
title:               'CMSE 822: Parallel Computing'
tagline:             'Parallel Computing, Fall 2020'
description:         'Michigan State University - Computational Mathematics, Science, and Engineering 822: Parallel Computing'
url:                 https://cmse822.github.io
github:
  repository_name:   https://github.com/cmse822

# About/contact
author:
  name:              Sean Couch
  url:               http://pa.msu.edu/~couch
  email:             scouch@msu.edu

theme: jekyll-theme-cayman
