# Setup
title:               'CMSE 822'
tagline:             'Parallel Computing, Fall 2018'
description:         'Computational Mathematics, Science, and Engineering 822 - Parallel Computing. A graduate-level course covering the fundamentals of computing on parallel architectures.'
url:                 http://cmse822.github.io
github:
  repo: https://classroom.github.com/classrooms/21065124-cmse-822-parallel-computing

# About/contact
author:
  name:              Sean Couch
  url:               http://pa.msu.edu/~couch
  email:             couch@pa.msu.edu

theme: jekyll-theme-cayman
